(define (sumDigits n)
  (let ((r 0))
    (while (> n 0)
      (set! r (+ r (remainder n 10)))
      (set! n (quotient n 10)))
  r))

(define (some-sums N A B)
  (let ((s 0) (x 0))
    (dotimes (i (+ N 1))
      (set! x (sumDigits i))
      (if (and (>= x A) (<= x B))
        (set! s (+ s i))))
  s))

(let* ((N (read))
       (A (read))
       (B (read)))
  (display (some-sums N A B)))
